pipeline {
    agent {
        label 'docker'
    }
    environment {
        IMAGE = 'simple-api'
        TAG = 'v0.1'
        HUB_SERVER = 'hub.docker.com'
        KUBECONFIG = '/home/ubuntu/.kube/config'
        HUB_COMMON_CREDS = credentials('dockerhub')
    }
    stages {  
        stage('Build docker image...') {
            steps {
                sh 'echo "build docker images..."'
                sh '''
                    #!/bin/bash
                    docker build --rm -t local/simple-api:v0.1 -f 2/Dockerfile .
                '''
            }
        } 
        stage('Login to docker registry...') {
            steps {
                sh '''
                    #!/bin/bash
                    /usr/bin/docker login -u $HUB_COMMON_CREDS_USR -p $HUB_COMMON_CREDS_PSW $HUB_SERVER
                '''
            }
        }
        stage('Tag docker image...') {
            steps {
                sh '''
                    #!/bin/bash
                    /usr/bin/docker tag local/$IMAGE:$TAG $HUB_SERVER/$IMAGE:$TAG
                '''
            }
        }   
               
        stage('Push docker image...') {
            steps {
                sh '''
                    #!/bin/bash
                    /usr/bin/docker push $HUB_SERVER/$IMAGE:$TAG
                '''
            }
        } 
        stage('Logout from docker registry...') {
            steps {
                sh '''
                    #!/bin/bash
                    /usr/bin/docker logout $HUB_SERVER
                '''
            }
        } 

        stage('Deploy workload to k8s cluster...') {             
            steps {
                sh 'echo "Deploy workload to k8s cluster..."'
                sh '''
                    #!/bin/bash
                    echo 'test'
                '''
            }
                
        }   
    } 
}