apiVersion: v1
kind: Service
metadata:
  name: simple-api-svc
  namespace: simple-api
spec:
  type: NodePort
  selector:
    app: simple-api
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500